version: "3.1"
services:
  geth-server:
    image: ethereum/client-go:v1.8.27
    ports:
      - 8545:8545
    container_name: geth-server
    command: --rinkeby --rpc --rpcapi="eth,net,web3,personal,txpool" --rpcaddr "0.0.0.0"
  mongo:
    image: mongo:3.6.22
    ports:
      - 27017:27017
  redis:
    image: redis:6.0.10
    ports:
      - 6379:6379